#!/bin/bash
# The installer must be ran on an Arch Linux host.

if cat /etc/os-release | grep "ID=arch"; then
   true
else
   echo "These scripts only work on Arch Linux"
   exit 1
fi

echo "Cloning into aurbuilder..."
cd $HOME
sudo pacman -S --needed --noconfirm git base-devel
git clone https://github.com/archlinuxir/aurbuilder.git
mv aurbuilder/* ./ && rm -r aurbuilder

echo "Installing aurbuilder to /usr/bin"
sudo mv aurbuilder aurdget aurfbuild aurtester aureupdate aurgupdater aurupdater /usr/bin
mkdir $HOME/logs && mkdir $HOME/logs/update && mkdir $HOME/logs/build
rm README.md aurbuilder-install -f

echo "Installing yay..."
git clone https://aur.archlinux.org/yay.git
cd yay && sudo makepkg -si && cd .. && rm -r yay

echo "Making required directories with required permission"

sudo mkdir /build && sudo mkdir -p /archlinuxir/x86_64
sudo chown $USER:$USER -R /build && sudo chown $USER:$USER -R /archlinuxir

echo "Installing other required packages"
sudo pacman -Syu --noconfirm && sudo pacman -S --noconfirm nvchecker
yay --noconfirm --noeditmenu --removemake --needed -S pacaur

if sudo cat /etc/sudoers | grep pacman && sudo cat /etc/sudoers | grep echo && sudo cat /etc/sudoers | grep mv >> /dev/null; then
   echo "Did not add sudoers entries."
else
   echo "Adding needed entries to sudoers."
   # Save username of current user to a file so that it can be used later.
   whoami > /tmp/whoami
   ECHO=$(which echo)
   MV=$(which mv)
   PACMAN=$(which pacman)
   YAY=$(which yay)
   sudo su -c 'export WHOAMI=$(cat /tmp/whoami) && echo "$WHOAMI ALL=(ALL) NOPASSWD:'$ECHO'" >> /etc/sudoers'
   sudo su -c 'export WHOAMI=$(cat /tmp/whoami) && echo "$WHOAMI ALL=(ALL) NOPASSWD:'$MV'" >> /etc/sudoers'
   sudo su -c 'export WHOAMI=$(cat /tmp/whoami) && echo "$WHOAMI ALL=(ALL) NOPASSWD:'$PACMAN'" >> /etc/sudoers'
   sudo su -c 'export WHOAMI=$(cat /tmp/whoami) && echo "$WHOAMI ALL=(ALL) NOPASSWD:'$YAY'" >> /etc/sudoers'
   rm -f /tmp/whoami
   echo "pacman, yay, echo and mv have been added to sudoers."
fi

echo "Replace the key in keyfile.toml to your own key."
echo "Done"
