#!/bin/bash

# Sleeps exist to prevent a set of bugs from happening.
# I Use proxychains because without it downloading will be slow.
# If you want to run these set of scripts with an unprivileged user then:
# pacman, yay, echo and mv must be added to sudoers file.
# Also move all the scripts to /usr/bin or /usr/local/bin or any place which is in PATH.
# You can remove proxychains in these scripts if you don't need them.
# REPO_NAME, ARCH_DIR, LOGS_DIR, SOURCE_DIR and BUILD_DIR can be adjusted to your liking.
# If you have installed it via the installer then it probably has done everything for you.

BUILD_DIR="/build"
REPO_NAME="archlinuxir"
ARCH_DIR="/$REPO_NAME/x86_64"
LOGS_DIR="$HOME/logs/update"
SOURCE_DIR="$HOME/source"

sudo pacman -Syu --noconfirm
sleep 1s
cd $HOME

rm $SOURCE_DIR -rf
proxychains aurdget gnome-shell-extension-arc-menu-git
rm $SOURCE_DIR -rf
proxychains aurdget plymouth-git
rm $SOURCE_DIR -rf
proxychains aurdget vala-panel-appmenu-xfce-git
rm $SOURCE_DIR -rf
proxychains aurdget gnome-shell-extension-openweather-git
rm $SOURCE_DIR -rf
proxychains aurdget blueprint-compiler-git
rm $SOURCE_DIR -rf
proxychains aurdget gnome-text-editor-git
rm $SOURCE_DIR -rf
proxychains aurdget gnome-console-git
rm $SOURCE_DIR -rf
proxychains aurdget gnome-shell-extension-just-perfection-desktop-git
rm $SOURCE_DIR -rf
proxychains aurdget gnome-shell-extension-shell-configurator-git
rm $SOURCE_DIR -rf
proxychains aurdget amberol-git
rm $SOURCE_DIR -rf
proxychains aurdget libadwaita-git
rm $SOURCE_DIR -rf

cp $BUILD_DIR/*.pkg.tar.* $ARCH_DIR
echo "Updating the Database."
rm $ARCH_DIR/$REPO_NAME*
repo-add -R $ARCH_DIR/$REPO_NAME.db.tar.zst $ARCH_DIR/*.pkg.tar.zst > /dev/null 2>&1
echo "Database updated completed."
rm -rf $BUILD_DIR/*
find $LOGS_DIR -mindepth 1 -mtime +2 -delete
