#!/bin/bash
# I Use proxychains because without it downloading will be slow.
# If you want to run these set of scripts with an unprivileged user then:
# pacman, yay, echo and mv must be added to sudoers file.
# Also move all the scripts to /usr/bin or /usr/local/bin or any place which is in PATH.
# You can remove proxychains in these scripts if you don't need them.
# REPO_NAME, ARCH_DIR, LOGS_DIR, SOURCE_DIR and BUILD_DIR can be adjusted to your liking.
# If you have installed it via the installer then it probably has done everything for you.

PKG_FILE="$HOME/pkg"
REPO_NAME="archlinuxir"
ARCH_DIR="/$REPO_NAME/x86_64"
LOGS_DIR="$HOME/logs/update"
BUILD_DIR="/build"
SOURCE_DIR="$HOME/source"
PKGBUILD="$HOME/source/PKGBUILD"

cd $HOME
START=$(date +%s)
UPDATEDATE=$(date +'%Y-%m-%d-%H-%M-%S')
echo "Updating the system."
sudo pacman -Syu --noconfirm >> /dev/null

# This loop reads the file that countains our packages in my case its 'pkg'.

while IFS= read -r line; do

# Get last update date from pacaur and convert it to unix time.
# Pacaur and cower are deprecated but I decided to use it as it
# gave me just what i needed with a single command.

  LASTUPDATE=$(pacaur info $line | grep "Last Modified" | cut -c19-)
  UNIXLAST=$(date -d "$LASTUPDATE" +"%s")

# Add 14 hours to the last update time so if it does have any updates
# Our 6 hour cronjob will grab it (BUG: gets updated twice ).

  UNIXLAST6=$(($UNIXLAST + 50400))

# 50400 for 14 hours (60x60x14 seconds)

  if [[ $UNIXLAST6 -ge $START ]];
  then

    if [ "$line" == "tor-browser" ]
    then
	rm -rf $SOURCE_DIR
        proxychains aurdget tor-browser
        cd $HOME
        sed -i 's#https://dist.torproject.org/torbrowser/#https://tor.calyxinstitute.org/dist/torbrowser/#g' $PKGBUILD
        proxychains aurdget tor-browser
    else
        proxychains aurdget $line
        rm -rf $SOURCE_DIR && cd $ARCH_DIR
    fi
      echo $line >> $LOGS_DIR/Updated-$UPDATEDATE
  else
      echo "$line doesn't need to get updated."
  fi
done < $PKG_FILE

sleep 2s

# Copy built packages to webserver root and update the database.

cp $BUILD_DIR/*.pkg.tar.* $ARCH_DIR
echo "Updating the Database."
rm $ARCH_DIR/$REPO_NAME*
repo-add -R $ARCH_DIR/$REPO_NAME.db.tar.zst $AIR_DIR/*.pkg.tar.zst > /dev/null 2>&1
echo "Database updated completed."
rm -rf $BUILD_DIR/*
find $LOGS_DIR -mindepth 1 -mtime +2 -delete
